[tool.black]
line-length = 100
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:The _yaml extension module is now located at yaml._yaml:DeprecationWarning",
]
addopts = "--cov=. --cov-report=xml --cov-report=term --junitxml=pytest_report.xml"

[tool.coverage.run]
branch = true
omit = ["tests*"]
source = ["."]
[tool.poetry]
name = "mail-groene-maaiers"
version = "0.1.0"
description = "Using a Gsheet to extract names to send out reminder using email"
authors = ["Bart Dorlandt <bart@bamweb.nl>"]
license = "LICENSE"
readme = "README.md"
packages = [{include = "mail_groene_maaiers"}]

[tool.poetry.dependencies]
python = "^3.10"
google-api-python-client = "^2.76.0"
google-auth-httplib2 = "^0.1.0"
python-decouple = "^3.7"
rich = "^13.3.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = {extras = ["d"], version = "^23.1.0"}
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
mypy = "^0.991"
ruff = "^0.0.240"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py310"
extend-ignore = ["F401", "F403"]
extend-exclude = [".git","__pycache__","dist","build",".venv"]

[tool.ruff.mccabe]
max-complexity = 10