#!/usr/bin/env bash

set -o errexit
set -o pipefail

# minus sign: use default if unset
NAME="${NAME:-groene_maaiers}"
VERSION="${VERSION:-latest}"
REMOTE_PATH="${REMOTE_PATH:-/Volumes/docker/mail_groene_maaiers/}"

# If we're running in CI we need to disable docker_compose_tty allocation for docker compose
# commands that enable it by default, such as exec and run.
docker_compose_tty=""
docker_run_tty="-it"
if [[ ! -t 1 ]]; then
  docker_compose_tty="-T"
  docker_run_tty=""
fi


# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------
function _echo_run {
  echo "$1"
  # shellcheck disable=SC2091
  # shellcheck disable=SC2116
  $(echo "$1")
}

function _poetry {
  echo "poetry run $1"
  # shellcheck disable=SC2091
  # shellcheck disable=SC2116
  $(echo "poetry run $1")
}

function _nox_docker {
  cmd="docker run --platform linux/amd64 --rm -it -v $(pwd):/src bartdorlandt/nox_poetry $1 -f src/noxfile.py"
  echo "$cmd"
  # shellcheck disable=SC2091
  # shellcheck disable=SC2116
  $(echo "$cmd")
}

# -----------------------------------------------------------------------------
function install:dev {
   _echo_run "poetry install --with dev --sync"
}

function test {
	_poetry "ruff check ."
	_poetry "ruff format --diff ."
	_poetry "mypy . --junit-xml mypy_report.xml"
	_poetry "pytest --cov-report=html"
}

function fix {
	_poetry "ruff check . --fix"
	_poetry "ruff format . -v"
}

function nox {
  # -r, re-used existing virtualenv
	_nox_docker "nox -r"
}

function nox:tests {
	_nox_docker "nox -r -s tests"
}

function nox:lint {
	_nox_docker "nox -r -s lint"
}

function nox:typing {
	_nox_docker "nox -r -s typing"
}

function build {
  DOCKER_BUILDKIT=1 docker build --tag "${NAME}":"${VERSION}" .
}

function clean {
  docker rmi "${NAME}":"${VERSION}" --force
}

function rebuild {
  clean
  build
}

function mail {
  # shellcheck disable=SC2086
#  docker run ${docker_run_tty} --rm -v="$(pwd)":/local "${NAME}":"${VERSION}" sh -c 'python3 main.py'
  docker_image="bartdorlandt/mail_groene_maaiers"
  docker pull "${docker_image}":"${VERSION}"
  docker run ${docker_run_tty} --rm \
    -v ./.env:/app/.env \
    -v ./credentials.json:/app/credentials.json \
    "${docker_image}":"${VERSION}" main.py
}

function sync {
  rsync -avz credentials.json main.py run env.example "${REMOTE_PATH}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
