#!/usr/bin/env bash

set -o errexit
set -o pipefail

# minus sign: use default if unset
NAME="${NAME:-groene_maaiers}"
VERSION="${VERSION:-latest}"
REMOTE_PATH="${REMOTE_PATH:-/Volumes/docker/mail_groene_maaiers/}"

# If we're running in CI we need to disable docker_compose_tty allocation for docker compose
# commands that enable it by default, such as exec and run.
docker_compose_tty=""
docker_run_tty="-it"
if [[ ! -t 1 ]]; then
  docker_compose_tty="-T"
  docker_run_tty=""
fi


# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------
function _echo_run {
  echo "$1"
  # shellcheck disable=SC2091
  # shellcheck disable=SC2116
  $(echo "$1")
}

# -----------------------------------------------------------------------------
function install:dev {
   _echo_run "poetry install --with dev --sync"
}

function test {
	_echo_run "ruff ."
	_echo_run "mypy . --junit-xml mypy_report.xml"
	_echo_run "black --diff --color ."
	_echo_run "pytest"
}

function fix {
	_echo_run "black ."
	_echo_run "ruff . --fix"
}

function build {
  docker build --tag "${NAME}":"${VERSION}" .
}

function clean {
  docker rmi "${NAME}":"${VERSION}" --force
}

function rebuild {
  clean
  build
}

function mail {
  # shellcheck disable=SC2086
  docker run ${docker_run_tty} --rm -v="$(pwd)":/local "${NAME}":"${VERSION}" sh -c 'python3 groene_maaiers.py'
}

function sync {
  rsync -avz --exclude-from=sync_exclude.txt --delete . "${REMOTE_PATH}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
