version: "3"

env:
  TAGS: "all"
  DOCKER_USER: 'bartdorlandt'
  VERSION: 'latest'
  REMOTE_PATH: '/Volumes/docker/mail_groene_maaiers'

vars:
  docker_compose_tty: ""
  docker_run_tty: "-it"
  name: 'mail_groene_maaiers'

tasks:
  default: task --list-all --sort none

  test:
    desc: "Running python tests"
    deps: [pytest, mypy, ruff]

  python_fix:
    desc: "Run python formatters"
    aliases: [fix]
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format . -v

  pytest:
    desc: "Run pytest"
    cmds:
      - uv run pytest -v

  mypy:
    desc: "Run mypy"
    cmds:
      - uv run mypy . --junit-xml mypy_report.xml --enable-incomplete-feature=NewGenericSyntax

  ruff:
    desc: "Run ruff"
    cmds:
      - uv run ruff check .
      - uv run ruff format --diff .

  docker_build:
    desc: "Build the docker image"
    aliases: [build, Dbuild, docker]
    cmds:
      - DOCKER_BUILDKIT=1 docker build --tag "{{.DOCKER_USER}}/{{.name}}":"{{.VERSION}}" .

  docker_clean:
    desc: "Clean the docker image"
    aliases: [clean_docker, Dclean]
    cmds:
      - docker rmi "{{.DOCKER_USER}}/{{.name}}":"{{.VERSION}}" --force

  docker_rebuild:
    desc: "Rebuild the docker image"
    aliases: [rebuild, Drebuild]
    cmds:
      - task: docker_clean
      - task: docker_build

  mail:
    desc: "Send the email"
    silent: true
    cmds:
      - ./mail.sh

  sync:
    desc: "Sync the files to the remote system"
    silent: true
    cmds:
      - rsync -avz credentials.json main.py mail.sh src justfile env.example --exclude '**/__pycache__' "{{.REMOTE_PATH}}"

  install_no_dev:
    desc: "Install the python dependencies"
    aliases: [install]
    cmds:
      - uv venv
      - uv sync --no-dev

  install_dev:
    desc: "Install the python dependencies"
    cmds:
      - uv venv
      - uv sync

  clean:
    desc: "Clean up the files and dirs"
    silent: true
    cmds:
      - rm -rf .venv .nox .ruff_cache .pytest_cache .mypy_cache .coverage htmlcov __pycache__ coverage.xml pytest_report.xml mypy_report.xml dist

  act_checks:
    desc: "Run checks with act, to test github actions"
    cmds:
      - act -j checks

  act_build:
    desc: "Run build with act, to test github actions"
    cmds:
      - act -j build

  act_push:
    desc: "Run push with act, to test github actions"
    cmds:
      - act -j push



