version: "3"

env:
  TAGS: "all"
  DOCKER_USER: bartdorlandt
  VERSION: latest
  REMOTE_PATH: "/Volumes/docker/mail_groene_maaiers"

vars:
  docker_compose_tty: ""
  docker_run_tty: "-it"
  name: mail_groene_maaiers

tasks:
  default:
    cmd: task -l
    silent: true

  run:
    desc: "Run the application"
    cmds:
      - uv run main.py

  run:test:
    desc: "Run the application in test mode, without sending emails"
    cmds:
      - EMAIL_ON=False uv run main.py

  tests:
    desc: "Running python tests"
    cmds:
      - task: test:ruff
      - task: test:typing
      - task: test:pytest

  format:fix:
    desc: "Run python formatters"
    aliases: [fix]
    cmds:
      - uv run ruff format . -v
      - uv run ruff check . --fix

  test:pytest:
    desc: "Run pytest"
    cmds:
      - uv run pytest -v {{.CLI_ARGS}}

  test:typing:
    desc: "Run static type checker"
    cmds:
      - uv run pyrefly check
      # --enable-incomplete-feature=NewGenericSyntax  # enabled by default in 3.14

  test:ruff:
    desc: "Run ruff"
    cmds:
      - uv run ruff check .
      - uv run ruff format --diff .

  sync:
    desc: "Sync the files to the remote system"
    silent: true
    cmds:
      - rsync -avz .python-version credentials.json env.example main.py pyproject.toml src Taskfile.yml uv.lock --exclude '**/__pycache__' "{{.REMOTE_PATH}}"
      #

  install:nodev:
    desc: "Install the python dependencies"
    aliases: [install]
    cmds:
      - uv sync --no-dev

  install:
    desc: "Install the python dependencies"
    cmds:
      - uv sync

  clean:
    desc: "Clean up the files and dirs"
    silent: true
    cmds:
      - rm -rf .venv .nox .ruff_cache .pytest_cache .coverage htmlcov __pycache__ coverage.xml pytest_report.xml dist

  act:checks:
    desc: "Run checks with act, to test github actions"
    cmds:
      - act -j checks

  act:build:
    desc: "Run build with act, to test github actions"
    cmds:
      - act -j build

  act:push:
    desc: "Run push with act, to test github actions"
    cmds:
      - act -j push
