# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - name: config venv
#        uses: abatilo/actions-poetry@v2.1.6
#        with:
#          python_version: 3.10.7
#          poetry_version: 1.3.2
#          args: config virtualenvs.in-project true

      - name: install
        uses: abatilo/actions-poetry@v2.1.6
        with:
          python_version: 3.10.7
          poetry_version: 1.3.2
          args: install
#      - name: Set up Python 3.10
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.10"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install -r requirements-dev.txt -U
      - name: Syntax
        run: |
          ruff .
#          flake8
          black --diff --color .
#          isort . --check --diff
          mypy . --junit-xml mypy_report.xml
      - name: Test with pytest
        run: |
          pytest
